CREATE USER 'poet'@'%' IDENTIFIED BY 'poet';

GRANT USAGE ON * . * TO 'poet'@'%' IDENTIFIED BY 'poet' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT ALL PRIVILEGES ON `poetry` . * TO 'poet'@'%';
